### ISSUE TITLE
Add derivative data for Guarani

### ISSUE THREAD

**Issue by hugolpz** [pln-fing-udelar/jojajovai#2]
- [ ] Corpora of Guarani sentences (monolingual)
- [ ] Guarani frequency wordlist

Even if not lemalized, could be of some use for later researches and open sources projects.

Feel free to assign these tasks to me.

**Comment by luischir** [comment]
Thanks for the suggestions. The monolingual part of the data in both languages is already easy to obtain from the csv file. As for you other suggestion, due to the morphological complexity of the language, we rather wait until we have a way to lemmatize the data so as to make a richer contribution to the corpus.
